eval_backend: OpenCompass
eval_config:
  datasets:
    - mmlu
    - ceval
    - ARC_c
    - gsm8k
  models:
    - openai_api_base: http://127.0.0.1:11434/v1/chat/completions
      path: Fin-Search                                
      temperature: 0.0